update app.etl_config set target_table_mapping = json_parse ('
[[{"source_col_name":"CompositeKey","target_col_name":"compositekey","target_col_datatype":"text"},{"source_col_name":"VendorName","target_col_name":"vendorname","target_col_datatype":"string"},{"source_col_name":"BidLineItemID","target_col_name":"bidlineitemid","target_col_datatype":"integer"},{"source_col_name":"LoanNumber","target_col_name":"loannumber","target_col_datatype":"integer"},{"source_col_name":"BidOrderNumber","target_col_name":"bidordernumber","target_col_datatype":"integer"},{"source_col_name":"BidSubmittedDate","target_col_name":"bidsubmitteddate","target_col_datatype":"date"},{"source_col_name":"WorkOrderNumber","target_col_name":"workordernumber","target_col_datatype":"integer"},{"source_col_name":"WorkOrderCompletedDate","target_col_name":"workordercompleteddate","target_col_datatype":"date"},{"source_col_name":"ItemCode","target_col_name":"itemcode","target_col_datatype":"string"},{"source_col_name":"BidLineItem","target_col_name":"bidlineitem","target_col_datatype":"string"},{"source_col_name":"TotalCharge","target_col_name":"totalcharge","target_col_datatype":"string"},{"source_col_name":"ServicerBidStatus","target_col_name":"servicerbidstatus","target_col_datatype":"string"},{"source_col_name":"HUDDenial","target_col_name":"huddenial","target_col_datatype":"string"},{"source_col_name":"HUDComment","target_col_name":"hudcomment","target_col_datatype":"text"},{"source_col_name":"ServicerBidTrackInitialCreateDate","target_col_name":"servicerbidtrackinitialcreatedate","target_col_datatype":"date"},{"source_col_name":"HazClaimFollowUpDate","target_col_name":"hazclaimfollowupdate","target_col_datatype":"date"},{"source_col_name":"WaitonHazClaim","target_col_name":"waitonhazclaim","target_col_datatype":"boolean"},{"source_col_name":"ServicerNotes","target_col_name":"servicernotes","target_col_datatype":"text"},{"source_col_name":"CelinkNotes","target_col_name":"celinknotes","target_col_datatype":"text"},{"source_col_name":"FiveBrosNotes","target_col_name":"fivebrosnotes","target_col_datatype":"text"},{"source_col_name":"ChangedByUser","target_col_name":"changedbyuser","target_col_datatype":"string"},{"source_col_name":"ChangedDate","target_col_name":"changeddate","target_col_datatype":"date"},{"source_col_name":"FieldChanged","target_col_name":"fieldchanged","target_col_datatype":"text"},{"source_col_name":"ChangedFrom","target_col_name":"changedfrom","target_col_datatype":"text"},{"source_col_name":"ChangedTo","target_col_name":"changedto","target_col_datatype":"text"},{"source_col_name":"FileDate","target_col_name":"filedate","target_col_datatype":"date"}],["compositekey"]]
')
where config_id = 632;


update app.etl_config set raw_table_mapping = json_parse ('
[{"required":"Yes","src_col_name":"CompositeKey","raw_col_name":"compositekey"},{"required":"Yes","src_col_name":"VendorName","raw_col_name":"vendorname"},{"required":"Yes","src_col_name":"BidLineItemID","raw_col_name":"bidlineitemid"},{"required":"Yes","src_col_name":"LoanNumber","raw_col_name":"loannumber"},{"required":"Yes","src_col_name":"BidOrderNumber","raw_col_name":"bidordernumber"},{"required":"Yes","src_col_name":"BidSubmittedDate","raw_col_name":"bidsubmitteddate"},{"required":"Yes","src_col_name":"WorkOrderNumber","raw_col_name":"workordernumber"},{"required":"Yes","src_col_name":"WorkOrderCompletedDate","raw_col_name":"workordercompleteddate"},{"required":"Yes","src_col_name":"ItemCode","raw_col_name":"itemcode"},{"required":"Yes","src_col_name":"BidLineItem","raw_col_name":"bidlineitem"},{"required":"Yes","src_col_name":"TotalCharge","raw_col_name":"totalcharge"},{"required":"Yes","src_col_name":"ServicerBidStatus","raw_col_name":"servicerbidstatus"},{"required":"Yes","src_col_name":"HUDDenial","raw_col_name":"huddenial"},{"required":"Yes","src_col_name":"HUDComment","raw_col_name":"hudcomment"},{"required":"Yes","src_col_name":"ServicerBidTrackInitialCreateDate","raw_col_name":"servicerbidtrackinitialcreatedate"},{"required":"Yes","src_col_name":"HazClaimFollowUpDate","raw_col_name":"hazclaimfollowupdate"},{"required":"Yes","src_col_name":"WaitonHazClaim","raw_col_name":"waitonhazclaim"},{"required":"Yes","src_col_name":"ServicerNotes","raw_col_name":"servicernotes"},{"required":"Yes","src_col_name":"CelinkNotes","raw_col_name":"celinknotes"},{"required":"Yes","src_col_name":"FiveBrosNotes","raw_col_name":"fivebrosnotes"},{"required":"Yes","src_col_name":"ChangedByUser","raw_col_name":"changedbyuser"},{"required":"Yes","src_col_name":"ChangedDate","raw_col_name":"changeddate"},{"required":"Yes","src_col_name":"FieldChanged","raw_col_name":"fieldchanged"},{"required":"Yes","src_col_name":"ChangedFrom","raw_col_name":"changedfrom"},{"required":"Yes","src_col_name":"ChangedTo","raw_col_name":"changedto"},{"required":"Yes","src_col_name":"FileDate","raw_col_name":"filedate"}]
')
where config_id = 632;

